<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0 (Python 3.9.13 on linux)" generated="20221101 17:47:11.399" rpa="false" schemaversion="3">
<suite id="s1" name="Complete Purchase" source="/nfs/homes/vcedraz-/automation_tests_practice/complete_purchase_test/complete_purchase.robot">
<test id="s1-t1" name="Scenario: complete_purchase" line="11">
<kw name="Open Browser" library="SeleniumLibrary" type="SETUP">
<arg>${URL}</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20221101 17:47:11.627" level="FAIL">Variable '${URL}' not found.</msg>
<status status="FAIL" starttime="20221101 17:47:11.626" endtime="20221101 17:47:11.627"/>
</kw>
<kw name="Close Browser" library="SeleniumLibrary" type="TEARDOWN">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20221101 17:47:11.627" endtime="20221101 17:47:11.627"/>
</kw>
<status status="FAIL" starttime="20221101 17:47:11.626" endtime="20221101 17:47:11.628">Setup failed:
Variable '${URL}' not found.</status>
</test>
<status status="FAIL" starttime="20221101 17:47:11.400" endtime="20221101 17:47:11.629"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Complete Purchase">Complete Purchase</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221101 17:47:11.625" level="ERROR">Error in file '/nfs/homes/vcedraz-/automation_tests_practice/complete_purchase_test/complete_purchase.robot' on line 7: Resource file '../page_objects/locators.robot' does not exist.</msg>
</errors>
</robot>
